---
  - name:  checking if yum packages are up to date on remote hosts
    hosts: dev_servers
    remote_user: root

    tasks:  
      - name: Update all packages
        when:  ( ansible_distribution == "CentOS" )
        yum:
          name: '*'
          state: latest
          update_cache: yes