--- 
  - name: install nginx on ubuntu
    hosts: web
    tasks: 
      - name: ensure nginx is at latest version
        apt: 
          name: nginx
          state: latest
      - name: start nginx
        service: 
          name: nginx
          state: started
          enabled: yes          