---
  - name: install vim package  on both servers
    hosts: prod 

    tasks:
      - name: yum install vim package centos
        yum:
          name: vim
          state: latest # present or installed
        when: 
          #- ansible_facts['distribution'] == "CentOS"
          - ansible_facts['hostname'] == "centos"
          
      - name: apt install vim package ubuntu
        apt:
          name: vim
          state: latest # present or installed
        when: 
          #- ansible_facts['distribution'] == "Ubuntu" 
          - ansible_facts['hostname'] == "ubuntu-2"