---
  - name:  checking if apache is installed if not install it
    hosts: dev_servers
    remote_user: root
    
    tasks:
      - name: Checking if apache is installed
        package_facts:
          manager: "auto"
      - name: "httpd test result"
        debug: 
          msg: "httpd NOT found"
        when: "'httpd' not in ansible_facts.packages"
   
      - name: Install httpd
        yum:
          name: httpd
          state: latest      
      - name: ensure httpd enabled and running
        systemd:
          name: httpd
          state: started 
          enabled: yes  

                 