---
  - name: rebooting remote hosts 
    hosts: dev_servers 
    remote_user: root

    tasks:
      - name: reboot a CentOS machine 
        reboot:
          msg: "reboot initiated by Ansible"
          connect_timeout: 5
          reboot_timeout: 300
          pre_reboot_delay: 0
          post_reboot_delay: 30
          test_command: uptime
